### ISSUE TITLE
Specific letters not working with Shift

### ISSUE THREAD

**Issue by gfarmer1** [ZitaoTech/BB9900-USB_BLE_Keyboard#3]
V, B, and X do not work when holding the shift key (not capslock)

**Comment by ZitaoTech** [comment]
Hi, because the keyboard has no integrated diodes, there might be some ghost typing when you press some keys together, I have uploaded another firmware with the sticky shift feature. You can try it and see if you fits for you.

You can also check the newly added documentation about the explanation for this:
https://github.com/ZitaoTech/BB9900-USB_BLE_Keyboard/tree/main/Firmware

**Comment by gfarmer1** [comment]
Thank you. That explains it. I like the sticky keys idea, though I haven't had the opportunity to download the new firmware and try it.
